# Generated by Django 3.1.2 on 2020-10-26 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('count', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(4)])),
                ('mode', models.IntegerField(blank=True, default=1, null=True)),
                ('difficulty', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
                ('showagain', models.BooleanField(default=True, null=True)),
                ('start', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'Room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'UserRoom',
                'managed': False,
            },
        ),
    ]
